{% set name = "openff-bespokefit" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openforcefield/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pydantic =1
    - pyyaml
    - tqdm
    - rich
    - click >=8.0.0
    - click-option-group
    - rdkit
    - openff-utilities
    - openff-toolkit >=0.15
    - openff-interchange
    - openff-units =0.2
    - openff-forcefields
    - openff-qcsubmit >=0.50.1
    - forcebalance =1.9.6
    # setuptools pin is for https://github.com/leeping/forcebalance/issues/307
    - setuptools <82
    - openff-fragmenter-base >=0.1.2
    - openmm >=7.6.0
    - qcportal >=0.50
    - qcengine >=0.25.0,<0.50
    - qcelemental >=0.25.1,<0.50
    - chemper
    - geometric =1
    - torsiondrive
    - uvicorn
    - fastapi
    - starlette
    - celery >=5.0.0
    - httpx
    - redis-server
    # Downpin from https://github.com/openforcefield/openff-bespokefit/pull/426/changes
    - redis-py <7.2
  run_constrained:
    - h5py >=3.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - openff.bespokefit
  commands:
    - openff-bespoke --help

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for the generation of bespoke SMIRNOFF format parameters for individual molecules.
  dev_url: https://github.com/openforcefield/openff-bespokefit

extra:
  recipe-maintainers:
    - j-wags
    - mattwthompson
    - jthorton
    - SimonBoothroyd
    - Yoshanuikabundi 
